debug: false

# List of game mode where the player is boosted on road blocks.
# Default: SURVIVAL, CREATIVE
enabled_gamemode:
  - SURVIVAL
  - CREATIVE

# Road blocks speed bonus per animal and per block.
# Values need to be > -1.0.
# 0 = default speed, 0.5 = 50% faster, -0.3 = 30% slower, 1.0 = 100% faster, 3.0 = 300% faster etc.
speed_bonus:
  HORSE:
    SUSPICIOUS_GRAVEL: 0.5
    GRAVEL: 0.3
    SAND: -0.3
  CAMEL:
    SUSPICIOUS_SAND: 0.4
    SAND: 0.2